[ { geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png',
    id: 'ce4ffe228ab7ad49bb050defe68b3d28cc879c4a',
    name: 'Sydney Showboats',
    opening_hours: { open_now: false, weekday_text: [] },
    photos: [ [Object] ],
    place_id: 'ChIJjRuIiTiuEmsRCHhYnrWiSok',
    rating: 4.3,
    reference: 'CnRkAAAA74qM22z42w-JToHJw0hTzzXSal8ovuQCPg9bWnla2O6DpZxQF1sv3jnJt3marmgqh6i3p8-P03D1_fmKQ5fb3c4xvpgepi2WW3WDKoQ7r9HDHpxMZ3xdXOay-HQGi4-4lDEWR1WghsGHIPMCZOUsFhIQB3nLajwrQUX8qQl_wg4KzxoU5mc692rKT7IYm-QS8ETSV1a-_6E',
    scope: 'GOOGLE',
    types: 
     [ 'travel_agency',
       'restaurant',
       'food',
       'point_of_interest',
       'establishment' ],
    vicinity: 'King Street Wharf 5, Lime Street, Sydney' },
  { geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png',
    id: '3458f23c154e574552e0722773a46f384816b241',
    name: 'Vagabond Cruises',
    opening_hours: { open_now: false, weekday_text: [] },
    photos: [ [Object] ],
    place_id: 'ChIJLfySpTOuEmsRMFymbMkVkOE',
    rating: 4.1,
    reference: 'CnRkAAAAwwojbFVjeCTSliQIC5cULFwBthfi-rDq3YjLuU1yq8GB-yucFUhS_cFc4X74_xuLaVNPm3tE78mkk6ujfKTT8VwC5eR2H89ZCxPytCal2uK1om1SfBQ4ka_smwSVvexIM5h5Hi35zxfy-lt8PdT4CBIQHwwIaiHZyJzTwaLSgf-gSBoUBw7bhrIYWpl3B1E4Ux9VIwqUpHk',
    scope: 'GOOGLE',
    types: 
     [ 'travel_agency',
       'restaurant',
       'food',
       'point_of_interest',
       'establishment' ],
    vicinity: '37 Bank Street, Pyrmont' },
  { geometry: { location: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png',
    id: 'a97f9fb468bcd26b68a23072a55af82d4b325e0d',
    name: 'Australian Cruise Group',
    opening_hours: { open_now: false, weekday_text: [] },
    photos: [ [Object] ],
    place_id: 'ChIJrTLr-GyuEmsRBfy61i59si0',
    reference: 'CnRqAAAAvGWNmltQfLnClHcO3jgRVW7iNf_MJboKfcYfKQTU2zTjm04icXwGRTSLqai9rqGI8E_W0XgoTvBOS4L65779owURxUjfqeVZzKvwpDbmQE2byFRqavXJeyklYKBk-IcI91l4QeqdRJwJ6j9wGlztZxIQ55ZH1ZEwbgPMJseJYO5prhoUuErCvK9HAM3Qcd_kpaNdyKDgnXc',
    scope: 'GOOGLE',
    types: 
     [ 'travel_agency',
       'restaurant',
       'food',
       'point_of_interest',
       'establishment' ],
    vicinity: '32 The Promenade, King Street Wharf 5, Sydney' },
  { geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png',
    id: '21a0b251c9b8392186142c798263e289fe45b4aa',
    name: 'Rhythmboat Cruises',
    photos: [ [Object] ],
    place_id: 'ChIJyWEHuEmuEmsRm9hTkapTCrk',
    rating: 4.2,
    reference: 'CnRmAAAA-_-oswm-oCCnAWz5LPJ5pBx7XhP5OEDejIFMbAVIfOClMfGZIlbPFXBaGhTTQor2gASG6cCynGbx1O7IGyVs11hw9jIIkPMSYoTMFJMih_pYonsUCuwdcfdwyNQjECokHckRxNa9j53k5B5iNel0ExIQZ5Wb35dIswmtYPrM252f5xoUXK6692uP0VhetOkDICj6vH51VAQ',
    scope: 'GOOGLE',
    types: 
     [ 'travel_agency',
       'restaurant',
       'food',
       'point_of_interest',
       'establishment' ],
    vicinity: 'King Street Wharf, King Street, Sydney' },
  { geometry: { location: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png',
    id: 'b0277cade7696e575824681aba949d68814f9efe',
    name: 'Sydney New Year\'s Eve Cruises',
    opening_hours: { open_now: false, weekday_text: [] },
    photos: [ [Object] ],
    place_id: 'ChIJ__8_hziuEmsR27ucFXECfOg',
    reference: 'CoQBcQAAAM1EfD5EtwqCyGtPzNWi7wGqWYJ6AxHqLmfQQw87rCyntBM24wz11sjR-cr4ymAOY-OlVRv2I71obd5Q_E6H11xk3fPMwTi4uigst63C1NODkXGxQTsGLx-Gv3liSRaGoyVI7ca-HErszFjUpqYILzei_L9GP0aIoq8t9hn-mPKwEhCnh3liuZE2ra3k5S9-ScXIGhSp1nNcLiLbRlsPm52zIdj8p9nqgQ',
    scope: 'GOOGLE',
    types: 
     [ 'travel_agency',
       'restaurant',
       'food',
       'point_of_interest',
       'establishment' ],
    vicinity: '32 The Promenade, King Street Wharf 5, Sydney Nsw 2000, Sydney' },
  { geometry: { location: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    id: 'c620902a8565dd4c4d605fecbe4f9b585d881b62',
    name: 'Blue Line Cruises',
    place_id: 'ChIJvwSIiTiuEmsR8hEazPa4W7U',
    reference: 'CnRlAAAAAZEjff2uiPQ3zDVZKYPU9BH6xjsTOtKlGHNblB0VJCCle45caIAngo3TI8Kb0LNfRNVTx5jxRJdFzGIX8nqRf7F1UoVVuzovWEYItM36GpOc4EvZ6vaeZwotuwi4626938RU2ri7aGo7I-J5aAXnbRIQmXj8XnAOmKg86VwEsy5AyxoUgcQeMZEk9gSAkwK6LfIFTJMGHZ4',
    scope: 'GOOGLE',
    types: [ 'restaurant', 'food', 'point_of_interest', 'establishment' ],
    vicinity: 'Australia' } ]